In [1]:
import sys
sys.path.append('/cr/users/filip/bin')

from utils.binaries import *
from utils.plotting import *

17:49:11 [INFO] utils          -- ( +1375ms) -- import logging
17:49:11 [INFO] utils.binaries -- (  +178ms) -- import numpy as np
17:49:12 [INFO] utils.binaries -- (  +362ms) -- import pandas as pd
17:49:12 [INFO] utils.binaries -- (    +3ms) -- import binaries.tools as binaries
17:49:12 [INFO] utils.plotting -- (  +504ms) -- import matplotlib.pyplot as plt
17:49:13 [INFO] utils.plotting -- (  +403ms) -- import seaborn as sns
17:49:13 [DBUG] utils.plotting -- (   +14ms) -- font size set to 4
17:49:13 [DBUG] utils.plotting -- (    +1ms) -- figure size set to [2.4, 1.2]
17:49:13 [DBUG] utils.plotting -- (    +0ms) -- plotting style set to `notebook`.
17:49:13 [INFO] utils.plotting -- (    +3ms) -- import plotting.tools as plot

In [2]:
col_names = [
    "runid",
    "telescope",
    "stepsize_cm",
    "date",
    "source",
    "ledCurrent_mA",
    "forDB",
    "jobfile",
    "comment",
]

runlist_nov = pd.read_csv(
        '/cr/users/filip/projects/XYScanner/xy-calibration/config/calib_runlists/calib_runs_2023-11.list', sep=";", names=col_names, skipinitialspace=True, comment="#"
    )

runlist_nov

,runid,telescope,stepsize_cm,date,source,ledCurrent_mA,forDB,jobfile,comment
0,15918m23,co5,0,2023-11-07,NaN,0.0,0,NaN,Cal A
1,15918m24,co6,0,2023-11-07,NaN,0.0,0,NaN,Cal A
2,15919,co5,0,2023-11-07,NaN,0.0,0,NaN,Cal A open shutter
3,15920x,co5,6,2023-11-07,OLO,15.9,1,NaN,NaN
4,15923,co5,0,2023-11-07,NaN,0.0,0,NaN,Cal A open shutter
...,...,...,...,...,...,...,...,...,...
75,15990,co5,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter
76,6100,he2,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter
77,6101,he2,6,2023-11-16,OLO,15.9,1,job_HEAT_bay2_hex_s60_r0-1300_cut.txt,"incomplete run, 1319 events"
78,6102,he2,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter
79,6103m26,he2,0,2023-11-16,NaN,0.0,0,NaN,Cal A

In [3]:
for _id, row in runlist_nov.iterrows():
    if row.comment == "Cal A":
        runlist_nov.drop(_id, inplace=True)

runlist_nov

,runid,telescope,stepsize_cm,date,source,ledCurrent_mA,forDB,jobfile,comment
2,15919,co5,0,2023-11-07,NaN,0.0,0,NaN,Cal A open shutter
3,15920x,co5,6,2023-11-07,OLO,15.9,1,NaN,NaN
4,15923,co5,0,2023-11-07,NaN,0.0,0,NaN,Cal A open shutter
5,15924,co6,0,2023-11-07,NaN,0.0,0,NaN,Cal A open shutter
6,15925x,co6,6,2023-11-07,OLO,15.9,1,NaN,NaN
7,15927,co6,0,2023-11-07,NaN,0.0,0,NaN,Cal A open shutter
11,15930,co4,0,2023-11-08,NaN,0.0,0,NaN,Cal A open shutter
12,15934x,co4,6,2023-11-08,OLO,15.9,1,NaN,NaN
13,15939,co4,0,2023-11-08,NaN,0.0,0,NaN,Cal A open shutter
14,15940,co3,0,2023-11-08,NaN,0.0,0,NaN,Cal A open shutter
15,15941x,co3,6,2023-11-08,OLO,15.9,1,NaN,NaN
16,15950,co3,0,2023-11-08,NaN,0.0,0,NaN,Cal A open shutter
17,15951,co2,0,2023-11-08,NaN,0.0,0,NaN,Cal A open shutter
18,15952x,co2,6,2023-11-08,OLO,15.9,1,NaN,NaN
19,15955,co2,0,2023-11-08,NaN,0.0,0,NaN,Cal A open shutter
24,15958,co1,0,2023-11-09,NaN,0.0,0,NaN,Cal A open shutter
25,15959,co1,6,2023-11-09,OLO,15.9,1,NaN,NaN
26,15960,co1,0,2023-11-09,NaN,0.0,0,NaN,Cal A open shutter
27,6065,he3,0,2023-11-09,NaN,0.0,0,NaN,Cal A open shutter
28,6066,he3,6,2023-11-09,OLO,15.9,1,job_HEAT_bay3_hex_s60_r0-1300_cut.txt,NaN
29,6067,he3,0,2023-11-09,NaN,0.0,0,NaN,Cal A open shutter
30,6068,he1,0,2023-11-09,NaN,0.0,0,NaN,Cal A open shutter
31,6070,he1,6,2023-11-09,OLO,15.9,1,job_HEAT_bay1_hex_s60_r0-1300_cut.txt,NaN
32,6071,he1,0,2023-11-09,NaN,0.0,0,NaN,Cal A open shutter
36,6074,he2,0,2023-11-10,NaN,0.0,0,NaN,Cal A open shutter
37,6075,he2,6,2023-11-10,OLO,15.9,1,job_HEAT_bay2_hex_s60_r0_1300_cut,NaN
38,6076,he2,0,2023-11-10,NaN,0.0,0,NaN,Cal A open shutter
39,15966,co2,0,2023-11-11,NaN,0.0,0,NaN,Cal A open shutter
40,15967,co2,6,2023-11-11,OLO,15.9,1,job_Coihueco_bay2_hex_s60_r0-1300_cut.txt ...,NaN
41,15968,co2,0,2023-11-11,NaN,0.0,0,NaN,Cal A open shutter
45,12805,lm4,0,2023-11-13,NaN,0.0,0,NaN,Cal A open shutter
46,12806,lm4,6,2023-11-13,OLO,15.9,1,job_LosMorados_bay4_s60_r0-1250_cut.txt,NaN
47,12807,lm4,0,2023-11-13,NaN,0.0,0,NaN,Cal A open shutter
48,12808,lm3,0,2023-11-13,NaN,0.0,0,NaN,Cal A open shutter
49,12809,lm3,6,2023-11-13,OLO,15.9,1,job_LosMorados_bay3_hex_s60_r0-1250_cut.txt,NaN
50,12810,lm3,0,2023-11-13,NaN,0.0,0,NaN,Cal A open shutter
51,12811,lm6,0,2023-11-13,NaN,0.0,0,NaN,Cal A open shutter
52,12812,lm6,0,2023-11-13,NaN,0.0,0,NaN,Cal A open shutter
60,12817,lm6,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
61,12819,lm6,6,2023-11-14,OLO,15.9,1,job_LosMorados_bay6_s60_r0-1250_cut.txt,NaN
62,12820,lm6,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
63,12821,lm2,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
64,12822,lm2,6,2023-11-14,OLO,15.9,1,job_LosMorados_bay2_hex_s60_r0-1250_cut.txt,NaN
65,12823,lm2,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
66,12824,lm5,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
67,12825,lm5,6,2023-11-14,OLO,15.9,1,job_LosMorados_bay5_hex_s60_r0-1250_cut.txt,NaN
68,12826,lm5,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
69,12829,lm1,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
70,12830,lm1,6,2023-11-14,OLO,15.9,1,job_LosMorados_bay1_hex_s60_r0-1250_cut.txt,NaN
71,12831,lm1,0,2023-11-14,NaN,0.0,0,NaN,Cal A open shutter
73,15983,co5,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter
74,15984x,co5,6,2023-11-16,OLO,15.9,1,job_Coihueco_bay5_hex_s60_r0-1250_cut.txt,NaN
75,15990,co5,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter
76,6100,he2,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter
77,6101,he2,6,2023-11-16,OLO,15.9,1,job_HEAT_bay2_hex_s60_r0-1300_cut.txt,"incomplete run, 1319 events"
78,6102,he2,0,2023-11-16,NaN,0.0,0,NaN,Cal A open shutter

In [4]:
import glob
import os

for _id in runlist_nov['runid']:
    files = glob.glob(f'/cr/data02/AugerPrime/XY/2023nov_calA/*{_id}*')
    if files == []: continue
    os.remove(files[0])

### remove run files as well...

In [6]:
import os
src = '/cr/data02/AugerPrime/XY/2023nov_calA/'

with open('/cr/users/filip/projects/XYScanner/xy-calibration/config/calib_runlists/calA_runs_2023-11.list', 'w') as runlist:
    for cal in os.listdir(src):
        fields = cal.split('_')
        print(fields)
        runlist.write(f'{fields[2][2:]}{fields[1]};  he{int(fields[1][1:]) - 24}; 0; {fields[3][:10]}; "";     0.0;   0;  "{fields[3][11:16]}";                                               "Cal A"\n')

['Cal', 'Hw26-8332.ini']

IndexError: list index out of range